# These are supported funding model platforms
github: ['https://captchas.io', 'https://inditers.org']
patreon:
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt:
otechie: 
custom: 
